name: SmallRye Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1.4.3
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: Install graphviz
        run: sudo apt install graphviz

      - name: maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml

      - uses: actions/upload-artifact@v2
        name: tck-report
        with:
          name: tck-report
          path: testsuite/tck/target/surefire-reports

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [11]
    name: build with jdk ${{matrix.java}} windows

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml

  quality:
    needs: [build]
    if: github.event_name == 'push' && github.repository == 'smallrye/smallrye-open-api'
    runs-on: ubuntu-latest
    name: quality

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags --force

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: cache sonar
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: sonar
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: mvn -B verify --file pom.xml -Pcoverage javadoc:javadoc sonar:sonar -Dsonar.projectKey=smallrye_smallrye-open-api -Dsonar.login=$SONAR_TOKEN
